version: '3.8'

services:
  # Сервіс додатку
  web-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - app-network

  # Сервіс бази даних MongoDB
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
